# Generated by Django 3.0.1 on 2020-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200702_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='street',
            field=models.CharField(default='', max_length=250),
        ),
    ]
