# Generated by Django 3.0.1 on 2020-07-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200702_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250)),
                ('email', models.CharField(default='', max_length=250)),
                ('phonenum', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
