# Generated by Django 3.0.1 on 2020-07-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cyberolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='englisholym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='internationalspell',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mathsolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reasoningolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='scienceolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cyberolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='englisholym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='internationalspell',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='mathsolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='reasoningolym',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='scienceolym',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
