# Generated by Django 3.0.1 on 2020-07-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200712_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
