# Generated by Django 3.0.1 on 2020-07-12 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mathsolym', models.BooleanField(default=False, null=True)),
                ('scienceolym', models.BooleanField(default=False, null=True)),
                ('englisholym', models.BooleanField(default=False, null=True)),
                ('reasoningolym', models.BooleanField(default=False, null=True)),
                ('cyberolym', models.BooleanField(default=False, null=True)),
                ('internationalspell', models.BooleanField(default=False, null=True)),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
